### ISSUE TITLE
Error at end of srip processing

### ISSUE THREAD

**Issue by d36191** [rvidgen/clr#1]
HI All,

Since Im new to programming and GitHub, kindly ask to bar in mind any unprecision or basic mistake.

im running the stantadr vignette of the "rvidgen/clr: Tools for computational literature Review" and i get the message below:
"Error in source("C:/01_Books_R/R_CLR/clr-master/Vignette_Original.R",  : 
  C:/01_Books_R/R_CLR/clr-master/Vignette_Original.R:448:0: unexpected end of input
446: topicpapers
447: write.csv(topicpapers, file='topicpapers.csv', row.names=F"

Meanwhile, i have tried to adapt the basic vignette and made some changes to the local file and I get another type of error:

"> source('C:/01_Books_R/R_CLR/clr-master/Vignette2.R', echo=TRUE)
Error: '\R' is an unrecognized escape in character string starting ""C:\0_Books_R\R"
[Vignette2.txt](https://github.com/rvidgen/clr/files/1072186/Vignette2.txt)

Thank you in advance for your Support,

Vitor Correia

**Comment by rvidgen** [comment]
Hi
If you are using a PC then I think the slashes might go the other way, e.g.,
C:/01_Books_R on a Mac
C:\01_Books_R on a PC
Regards
Richard

**Comment by d36191** [comment]
Hi Richard,

Before anything, i really appreciate your quick response to my query. I had already tried that workaround and the error message is the same. I believe that this might be an initial error since i have already changed directory with Setwd(). Since at my university we don't have access to Scopus, only to Web of Science. I have prepared a group of files with xlsx, but I still have problems.
[Web_savedrecs.xlsx](https://github.com/rvidgen/clr/files/1076058/Web_savedrecs.xlsx)
[Web_savedrecs2.xlsx](https://github.com/rvidgen/clr/files/1076060/Web_savedrecs2.xlsx)
[Web_savedrecs3.xlsx](https://github.com/rvidgen/clr/files/1076062/Web_savedrecs3.xlsx)
[Web_savedrecs4.xlsx](https://github.com/rvidgen/clr/files/1076061/Web_savedrecs4.xlsx)
[Web_savedrecs5.xlsx](https://github.com/rvidgen/clr/files/1076059/Web_savedrecs5.xlsx)

Thank you in advance,
Vitor Correia

**Comment by rvidgen** [comment]
Hi Vitor
We only have CLR for scopus currently. If you email me (r.vidgen@unsw.edu.au)<mailto:r.vidgen@unsw.edu.au)> the WoS download file I will take a look and see what would be needed to read it.
Regards
Richard
